# name #

name: TestCalories

# configs #

configs:
  Debug: debug
  Release: release

# options #

options:
  bundleIdPrefix: testcalories.com
  deploymentTarget:
    iOS: 15.0
  generateEmptyDirectories: true
  defaultConfig: Debug
  developmentLanguage: en
  createIntermediateGroups: true
  
# settings #

settings:
  base:
      VERSION_NUMBER: "1.0"
      MARKETING_VERSION: '1.0.0'
      CURRENT_PROJECT_VERSION: 0
      VERSIONING_SYSTEM: apple-generic
      CODE_SIGN_STYLE: Manual
  configs:
    Debug:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: DEBUG
    Release:
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: RELEASE
      
# targets #

targets:
 TestCalories:
   type: application
   platform: iOS
   sources: TestCalories
   supportedDestinations: [iOS]
   settings:
     base:
        INFOPLIST_FILE: TestCalories/Resources/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_INCLUDE_ALL_APPICON_ASSETS: false
        TARGETED_DEVICE_FAMILY: 1
        INFOPLIST_KEY_CFBundleDisplayName: "TestCalories"
     configs:
       Debug:
         CODE_SIGN_STYLE: Manual
         DEVELOPMENT_TEAM:
         PROVISIONING_PROFILE_SPECIFIER: TestCalories Client Distr Provisioning Profile
         PRODUCT_BUNDLE_IDENTIFIER: testcalories.com
         PRODUCT_NAME: TestCalories
         DISPLAY_NAME: "TestCalories"
       Release:
         CODE_SIGN_IDENTITY: iPhone Distribution
         DEVELOPMENT_TEAM:
         PROVISIONING_PROFILE_SPECIFIER: TestCalories Client Distr Provisioning Profile
         PRODUCT_BUNDLE_IDENTIFIER: testcalories.com
         PRODUCT_NAME: TestCalories
         DISPLAY_NAME: "TestCalories"
   preBuildScripts:
   - path: Scripts/swiftformat.sh
     name: SwiftFormat
   postCompileScripts:
   - path: Scripts/swiftlint.sh
     name: SwiftLint
     
# schemes #

schemes:
  Debug:
    templates:
    - ConfigBasedScheme
    run:
      config: Debug
  Release:
    templates:
    - ConfigBasedScheme
    run:
      config: Release

# schemeTemplates #

schemeTemplates:
  ConfigBasedScheme:
    build:
      targets:
        TestCalories: all
    run:
      —Åonfig: "${scheme_name}"
    test:
      config: "${scheme_name}"
    profile:
      config: "${scheme_name}"
    analyze:
      config: "${scheme_name}"
    archive:
      config: "${scheme_name}"
